[SOAR-6570] Add handling for exceptions that are not ConnectionTestExceptions
rapid7/komand-plugin-sdk-python pull request #104
Opened 2022-04-06 15:46 UTC by tcheng-r7

### Description

This PR adds a new case in the envelope function (which prepares the output message for when the connection test endpoint gets hit) to handle non ConnectionTestException exceptions, adding an exception json to the response message.

### Motivation and Context

Previously, when a non ConnectionTestError exception would be thrown during a connection test, the response would not handle the exception and create an exception json in the response message.
![Screen Shot 2022-04-06 at 11 42 03 AM](https://user-images.githubusercontent.com/87387242/162014089-f024e218-ce27-4f7d-959e-19f6d8ac36e8.png)

Now, when a non ConnectionTestError exception is thrown during a connection test, the response creates an exception json in the response message.
![Screen Shot 2022-04-06 at 11 38 29 AM](https://user-images.githubusercontent.com/87387242/162013398-3f5b6ec2-cc0d-4b09-9b59-2cd3fa0fc7e5.png)

### How Has This Been Tested?

This is been tested locally by building an local sdk image and local plugin image, and then hitting the connection test endpoint (`http://0.0.0.0:10001/actions/uninstall_sensor/test`).

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [ ] I have updated the documentation accordingly (if changes are required).
- [ ] I have tested the changes locally.

### Miscellaneous Details:

2022-04-06 19:42 UTC, mberezin-r7 submitted a review, later dismissed

2022-04-06 22:03 UTC, mrinehart-r7 requested changes

2022-04-06 22:03 UTC, mrinehart-r7 commented on insightconnect_plugin_runtime/plugin.py
> +                        "cause": "SDK: Connection test failed.",
```suggestion
                        "cause": "Plugin connection test failed.",
```
"SDK" isn't too relevant to the user - it's not something they're likely to be familiar with. But, they do know what plugin means.

2022-04-07 15:27 UTC, mberezin-r7 approved these changes

2022-04-07 16:29 UTC, mrinehart-r7 approved these changes

2022-04-08 18:24 UTC, merged