[SOAR-9059] Update Connection Test endpoint
rapid7/komand-plugin-sdk-python pull request #109
Opened 2022-06-02 20:24 UTC by tcheng-r7

### Description

These changes update the (currently) unused connection test endpoint to better match the current expected output from the "actions/<random action name>/test" endpoint that is currently being used in the product for connection tests. This will allow us to hit this endpoint instead in the future for connection tests.

### Motivation and Context

Currently, when the a connection test is run, the endpoint that is being hit is "/actions/<random action name>/test". We want to move away from using this endpoint when running a connection test, using the v1 route "connection/test" instead.

### How Has This Been Tested?

![Screen Shot 2022-06-02 at 3 36 26 PM](https://user-images.githubusercontent.com/87387242/171731624-6b351093-4b3c-475b-b9cb-75fc0ae9b0fd.png)
![Screen Shot 2022-06-02 at 3 31 58 PM](https://user-images.githubusercontent.com/87387242/171731628-90314cb4-1d3d-4406-bb27-d84208ecee90.png)
![Screen Shot 2022-06-02 at 3 28 20 PM](https://user-images.githubusercontent.com/87387242/171731629-494a3a43-8e38-49c3-8b86-4dd158c62c86.png)
![Screen Shot 2022-06-02 at 3 26 21 PM](https://user-images.githubusercontent.com/87387242/171731630-669ba98f-e987-40b5-a17a-fcb7294f1485.png)

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [ ] I have updated the documentation accordingly (if changes are required).
- [ ] I have tested the changes locally.

### Miscellaneous Details:

2022-06-02 21:21 UTC, mrinehart-r7 commented on insightconnect_plugin_runtime/api/endpoints.py
> +            self.logger.debug("Request input: %s", input_message)
```suggestion
            self.logger.debug(f"Request input: {input_message}")
```
You may want to get rid of this, though - in production this may log credentials/secrets.

2022-06-02 21:22 UTC, mrinehart-r7 commented on insightconnect_plugin_runtime/api/endpoints.py
> +                if output.get("body").get("output") is None:
```suggestion
                if output.get("body", {}).get("output") is None:
```
You'll need the empty dict default to avoid getting a NoneError

2022-06-08 19:45 UTC, tcheng-r7 commented on insightconnect_plugin_runtime/plugin.py
> +            pass
This elif needs to kept in as without it, it will be caught by the else block on the next line and throw an unwanted exception.

2022-06-08 20:00 UTC, mrinehart-r7 submitted a review, later dismissed
LGTM! Just make sure to remove this comment here https://github.com/rapid7/komand-plugin-sdk-python/pull/109/files#diff-30d02443e7c30b5a00e61fdb6f3e00e3d0ea119bf022d2e71c64ecd22324e1b3R552

2022-06-08 20:38 UTC, mrinehart-r7 requested changes

2022-06-08 20:40 UTC, mrinehart-r7 approved these changes

2022-06-08 21:02 UTC, mrinehart-r7 submitted a review, later dismissed

2022-06-15 19:59 UTC, mberezin-r7 submitted a review, later dismissed

2022-06-15 20:02 UTC, mberezin-r7 approved these changes

2022-06-15 20:08 UTC, mrinehart-r7 approved these changes

2022-06-15 20:08 UTC, merged