[SOAR-14695] Plugin's Output - Add task_error property to task output to describe the error message when task fails
rapid7/komand-plugin-sdk-python pull request #133
Opened 2023-07-13 09:30 UTC by igorski-r7

### Description
Added additional optional returned tuple for plugin's tasks containing `status_code` and `error_message` in its structure ordered one to one. When the error occurs its necessary to additionally return tuple `(status_code, error)`  at the end of the return tuple which right now orders like

```python
return (output, state, has_more_pages, status_code, error_object)
```

For example when we are returning the data from task `run` method it needs to be done same as in that example to include the `status_code` and `error_object`:

```python
return [], {}, False, 200, PluginException()
```

Which corresponds to:

```python
return output, state, has_more_pages, status_code, error_object
```

The screen shows the actual plugin response:

<img width="953" alt="output" src="https://github.com/rapid7/komand-plugin-sdk-python/assets/99184344/0cc511d5-8495-4e0f-8bfd-efe6f0c088c0">

When `None` is returned in place of `error_object` from the task `run` method then the field named `exception` is not included in the plugin's response body.

### Motivation and Context
This change is required for C2C Tasks described in the ticket ([SOAR-14695](https://issues.corp.rapid7.com/browse/SOAR-14695)).

### How Has This Been Tested?
It was tested locally on `AWS S3` plugin with its tasks.

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:

- [X] I have updated the documentation accordingly (if changes are required).
- [X] I have tested the changes locally.

2023-07-13 10:14 UTC, TKuzas-R7 submitted a review, later dismissed

2023-07-13 10:18 UTC, cmcnally-r7 submitted a review, later dismissed
LGTM 😄

2023-07-14 14:56 UTC, mrinehart-r7 requested changes

2023-07-14 14:56 UTC, mrinehart-r7 commented on insightconnect_plugin_runtime/plugin.py
> +            output_message["task_error"] = task_error_dict
This should be put into `output_message["exception"]`, following the existing values that we set there (cause, assistance, data) like on https://github.com/rapid7/komand-plugin-sdk-python/pull/133/files#diff-450ad8b25b262beb9aad26f3e56f13f085b187ab349c2958d3169bc9a0358f8cR242-R244. 

Also we need to always return the status code from the third-party API regardless of whether or not an error occurred.

2023-07-17 07:12 UTC, igorski-r7 commented on insightconnect_plugin_runtime/plugin.py
> +            output_message["task_error"] = task_error_dict
I forgot to push the changes. My bad sorry 😄

2023-07-17 07:46 UTC, cmcnally-r7 approved these changes

2023-07-17 13:51 UTC, dlaverty-r7 approved these changes

2023-07-18 14:25 UTC, merged