SOAR:2386 Added implementation for event_start
rapid7/komand-plugin-sdk-python pull request #89
Opened 2020-09-07 15:55 UTC by gusingh-r7

### Description
- Add implementation for event_start

### Motivation and Context

### How Has This Been Tested?

### Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have updated the documentation accordingly (if changes are required).
- [ ] I have tested the changes locally.

### Miscellaneous Details:

2020-09-10 16:23 UTC, zyoutz-r7 requested changes
Sorry for th elast minute change.  `events` to `tasks` based on internal discussions.

2020-09-10 16:23 UTC, zyoutz-r7 commented on insightconnect_plugin_runtime/plugin.py
> +        self.events = {}
```suggestion
        self.tasks = {}
```

2020-09-10 16:23 UTC, zyoutz-r7 commented on insightconnect_plugin_runtime/plugin.py
> +    def add_event(self, event):
All `events` to change to `tasks` based on last week decision.

2020-09-11 06:06 UTC, zyoutz-r7 approved these changes

2020-09-15 21:03 UTC, zyoutz-r7 commented on insightconnect_plugin_runtime/api/endpoints.py
> +            msg = f"{p_type.capitalize()} name ({name_in_input_msg}) in input body is not matching with name ({name}) in route"
Good catch 👍

2020-09-15 21:04 UTC, zyoutz-r7 commented on insightconnect_plugin_runtime/api/schemas.py
> +    state = fields.Dict(required=True)
👍

2020-09-15 21:06 UTC, zyoutz-r7 commented on insightconnect_plugin_runtime/api/schemas.py
> +    action = fields.Str(required=True)
Should this be `task` instead?
```suggestion
    task = fields.Str(required=True)
```

2020-09-15 21:08 UTC, zyoutz-r7 commented on insightconnect_plugin_runtime/task.py
> +    Represents a Komand Task.
```suggestion
    Represents a Plugin Task.
```

2020-09-15 21:08 UTC, zyoutz-r7 requested changes
Couple suggestions but looking good!

2020-09-15 21:23 UTC, zyoutz-r7 approved these changes
Looking good! Are the unit test failures something we need to look into now or cleanup at the end?

2020-09-16 13:32 UTC, gusingh-r7 commented
> Looking good! Are the unit test failures something we need to look into now or cleanup at the end?

That is due to the `pytest` version. It has already been updated in the `master` branch with command injection changes.

2020-09-16 14:49 UTC, zyoutz-r7 commented
ah perfect, once we get this merged in can we make sure feature branch is updated with latest from master? 

lets get it in!

2020-09-16 15:10 UTC, merged