Add gevent worker class option
rapid7/komand-plugin-sdk-python pull request #90
Opened 2020-09-12 01:52 UTC by norenstrakh-r7

### Description

### Motivation and Context

### How Has This Been Tested?

### Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have updated the documentation accordingly (if changes are required).
- [ ] I have tested the changes locally.

### Miscellaneous Details:

2020-09-16 19:00 UTC, tschmidtke-r7 submitted a review, later dismissed
This is exciting! Personally I'd prefer the config file to be `GUNICORN_CONFIG_FILE`, but that's more of a nitpick.

2020-09-16 19:20 UTC, norenstrakh-r7 commented on samples/example/requirements.txt
> +gunicorn[gevent]
can be removed

2020-09-16 20:38 UTC, zyoutz-r7 requested changes
Looking good! Couple suggestions

2020-09-16 20:38 UTC, zyoutz-r7 commented on dockerfiles/3-38-slim
> +
```suggestion
```

2020-09-16 20:38 UTC, zyoutz-r7 commented on dockerfiles/3-38-slim
> +RUN apk update
Can we get a comment added here for why the dependencies are necessary

2020-09-16 20:38 UTC, zyoutz-r7 commented on insightconnect_plugin_runtime/server.py
> +                "workers": workers,
Are there any unintended side effects  if someone were to set workers > 1 along with `gevent` class?

2020-09-16 20:38 UTC, zyoutz-r7 commented on insightconnect_plugin_runtime/server.py
> +            with open(os.environ.get("GUNICORN_CFG_FILE")) as gf:
Love this addition! Will make it that much easier to investigate other settings that are made available 🔥

2020-09-16 20:38 UTC, zyoutz-r7 commented on samples/example/bin/icon_example
> +        from gevent import monkey
More for icon-plugin changes but can we make sure a comment is added here around why this order of imports is necessary?

2020-09-16 20:38 UTC, zyoutz-r7 commented on samples/example/bin/icon_example
> +    elif 'http' in argv and 'gevent' in argv and not os.environ.get("GUNICORN_CFG_FILE"):
Do we need the addition `and not` condition for this? Could we ever hit this?

2020-09-16 20:38 UTC, zyoutz-r7 commented on samples/example/requirements.txt
> +gunicorn[gevent]
Already part of setup.py for runtime.  Not needed for each plugin
```suggestion
```

2020-09-16 20:40 UTC, zyoutz-r7 commented on dockerfiles/3-38-slim
>  			sdk=python \
And just for confirmation, no changes necessary to the 3-38 (ubuntu) docker file?

2020-09-16 20:49 UTC, norenstrakh-r7 commented on insightconnect_plugin_runtime/server.py
> +                "workers": workers,
no , there is not, gunicorn will fork another worker, I actually tried it.

2020-09-16 20:50 UTC, norenstrakh-r7 commented on samples/example/bin/icon_example
> +    elif 'http' in argv and 'gevent' in argv and not os.environ.get("GUNICORN_CFG_FILE"):
let me change this condition,  I think there is a room for improvement

2020-09-16 20:52 UTC, norenstrakh-r7 commented on dockerfiles/3-38-slim
>  			sdk=python \
yep,  I was able to build `whois` (which we already ranging as cloud-plugin in staging)  without making changes to the base image.

2020-09-16 21:29 UTC, norenstrakh-r7 commented
> This is exciting! Personally I'd prefer the config file to be `GUNICORN_CONFIG_FILE`, but that's more of a nitpick.

changed

2020-09-17 03:42 UTC, zyoutz-r7 commented on dockerfiles/3-38-slim
> +# Support Gevent dependencies
Not sure about ordering of comment
```suggestion
# Support Gevent dependencies
RUN apk update
RUN apk add build-base libffi-dev openssl-dev

```

2020-09-17 03:42 UTC, zyoutz-r7 commented on insightconnect_plugin_runtime/server.py
> +                "workers": workers,
👍 perfect

2020-09-17 03:43 UTC, zyoutz-r7 commented on samples/example/bin/icon_example
> +    # If the worker is configured to run as gevent class
Thank you

2020-09-17 03:43 UTC, zyoutz-r7 commented on samples/example/bin/icon_example
> +        elif 'gevent' in argv:
👍

2020-09-17 03:44 UTC, zyoutz-r7 commented on README.md
> +export GUNICORN_CFG_FILE="./gcfg.json"
```suggestion
export GUNICORN_CONFIG_FILE ="./gcfg.json"
```

2020-09-17 03:44 UTC, zyoutz-r7 commented on README.md
> +To override Gunicorn config export environment variable GUNICORN_CFG_FILE pointing to json file with config
```suggestion
To override Gunicorn config export environment variable GUNICORN_CONFIG_FILE pointing to json file with config
```

2020-09-17 03:44 UTC, zyoutz-r7 requested changes
Couple small suggestions

2020-09-17 14:20 UTC, zyoutz-r7 approved these changes
Love it! Lets make sure @mrinehart-r7 and @gusingh-r7 also get a chance to give there feedback.

2020-09-17 14:40 UTC, gusingh-r7 submitted a review, later dismissed

2020-09-21 15:47 UTC, lmilby-r7 reviewed
Are we looking at including tests for these changes?

2020-09-21 15:47 UTC, jmcadams-r7 approved these changes

2020-09-23 18:41 UTC, zyoutz-r7 approved these changes

2020-09-23 18:45 UTC, gusingh-r7 approved these changes

2020-09-23 18:49 UTC, merged