Feature/events
rapid7/komand-plugin-sdk-python pull request #91
Opened 2020-09-22 17:52 UTC by gusingh-r7

### Description
- Add implementation and endpoints to support tasks.

### Motivation and Context

### How Has This Been Tested?

### Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have updated the documentation accordingly (if changes are required).
- [ ] I have tested the changes locally.

### Miscellaneous Details:

2020-09-29 03:16 UTC, zyoutz-r7 approved these changes
Looking good! Marked as DO NOT MERGE until we are ready to get it in.

2020-10-02 14:34 UTC, lmilby-r7 submitted a review, later dismissed

2020-10-02 17:53 UTC, zyoutz-r7 submitted a review, later dismissed
Want to make sure the tests all pass before merging but these changes look great 👍

2020-10-02 19:52 UTC, mrinehart-r7 requested changes

2020-10-02 19:52 UTC, mrinehart-r7 commented on insightconnect_plugin_runtime/variables.py
> +        return util.sample(self.schema)
Input, Output, and State all have the same `__init__`, `set`, `validate`, and `sample` functions - should/could that all be moved to a parent class that those three classes inherit from and override as necessary?

2020-10-02 21:22 UTC, gusingh-r7 commented on tests/unit/test_helpers.py
> -
Removing these test cases as https://httpstatus does not seem working.

2020-10-05 13:57 UTC, zyoutz-r7 approved these changes
🔥

2020-10-06 21:32 UTC, mrinehart-r7 approved these changes

2020-10-06 21:32 UTC, mrinehart-r7 approved these changes

2020-10-06 21:35 UTC, merged