Add helpful error messages in JSON
rapid7/komand-plugin-sdk-python pull request #93
Opened 2020-10-18 20:14 UTC by r7-mgorny

Add helpful error messages in JSON

### Description
Update the various Python SDK's to support returning the cause and assistance  and data messages as a new objectin the SDK's JSON output

### Motivation and Context
This will allow plugins to surface the user-friendly messages to the product which can then display them on the job page

### How Has This Been Tested?
## Assessment
### Run

<details>

```
{
  "body": {
    "error": "Connection test failed!\n\nCause description from ConnectionTestException Assistance description from ConnectionTestException Response was: Data description from ConnectionTestException",
    "exception": {
      "assistance": "Assistance description from ConnectionTestException",
      "cause": "Cause description from ConnectionTestException",
      "data": "Data description from ConnectionTestException"
    },
    "log": "Connect: Connecting...\nrapid7/Example Plugin:1.0.0. Step name: raise_error\nConnection test failed!\n\nCause description from ConnectionTestException Assistance description from ConnectionTestException Response was: Data description from ConnectionTestException\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.2.1-py3.8.egg/insightconnect_plugin_runtime/plugin.py\", line 332, in handle_step\n    output = self.start_step(\n  File \"/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.2.1-py3.8.egg/insightconnect_plugin_runtime/plugin.py\", line 482, in start_step\n    output = func(params)\n  File \"/usr/local/lib/python3.8/site-packages/example_rapid7_plugin-1.0.0-py3.8.egg/icon_example/actions/raise_error/action.py\", line 24, in run\n    raise ConnectionTestException(\ninsightconnect_plugin_runtime.exceptions.ConnectionTestException: Connection test failed!\n\nCause description from ConnectionTestException Assistance description from ConnectionTestException Response was: Data description from ConnectionTestException\n",
    "meta": {},
    "status": "error"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/example:1.0.0 --debug run < tests/raise_connection_test_exception.json
</summary>
</details>

<details>

```
{
  "body": {
    "error": "Sample message",
    "log": "Connect: Connecting...\nrapid7/Example Plugin:1.0.0. Step name: raise_error\nSample message\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.2.1-py3.8.egg/insightconnect_plugin_runtime/plugin.py\", line 332, in handle_step\n    output = self.start_step(\n  File \"/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.2.1-py3.8.egg/insightconnect_plugin_runtime/plugin.py\", line 482, in start_step\n    output = func(params)\n  File \"/usr/local/lib/python3.8/site-packages/example_rapid7_plugin-1.0.0-py3.8.egg/icon_example/actions/raise_error/action.py\", line 30, in run\n    raise Exception(\"Sample message\")\nException: Sample message\n",
    "meta": {},
    "status": "error"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/example:1.0.0 --debug run < tests/raise_exception.json
</summary>
</details>

<details>

```
{
  "body": {
    "error": "An error occurred during plugin execution!\n\nCause description from PluginException Assistance description from PluginException Response was: Data description from PluginException",
    "exception": {
      "assistance": "Assistance description from PluginException",
      "cause": "Cause description from PluginException",
      "data": "Data description from PluginException"
    },
    "log": "Connect: Connecting...\nrapid7/Example Plugin:1.0.0. Step name: raise_error\nAn error occurred during plugin execution!\n\nCause description from PluginException Assistance description from PluginException Response was: Data description from PluginException\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.2.1-py3.8.egg/insightconnect_plugin_runtime/plugin.py\", line 332, in handle_step\n    output = self.start_step(\n  File \"/usr/local/lib/python3.8/site-packages/insightconnect_plugin_runtime-4.2.1-py3.8.egg/insightconnect_plugin_runtime/plugin.py\", line 482, in start_step\n    output = func(params)\n  File \"/usr/local/lib/python3.8/site-packages/example_rapid7_plugin-1.0.0-py3.8.egg/icon_example/actions/raise_error/action.py\", line 18, in run\n    raise PluginException(\ninsightconnect_plugin_runtime.exceptions.PluginException: An error occurred during plugin execution!\n\nCause description from PluginException Assistance description from PluginException Response was: Data description from PluginException\n",
    "meta": {},
    "status": "error"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/example:1.0.0 --debug run < tests/raise_plugin_exception.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/Example Plugin:1.0.0. Step name: say_goodbye\n",
    "meta": {},
    "output": {
      "message": "Goodbye, goodbye"
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/example:1.0.0 --debug run < tests/say_goodbye.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/Example Plugin:1.0.0. Step name: say_hello\n",
    "meta": {},
    "output": {
      "message": "Hello, hello"
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/example:1.0.0 --debug run < tests/say_hello.json
</summary>
</details>

### Types of changes
- New feature

### Checklist:
- [ ] I have updated the documentation accordingly (if changes are required).
- [ ] I have tested the changes locally.

2020-10-19 15:56 UTC, mrinehart-r7 requested changes

2020-10-19 15:56 UTC, mrinehart-r7 commented on insightconnect_plugin_runtime/plugin.py
> +            if isinstance(ex, ConnectionTestException) or isinstance(ex, PluginException):
```suggestion
            if isinstance(ex, ConnectionTestException) or isinstance(ex, PluginException):
```
Should only need ConnectionTestException, I believe, since PluginException inherits from CTE

2020-10-19 15:56 UTC, mrinehart-r7 commented on samples/example/bin/icon_example
> -    #  if the plugin is running in Server mode(http).
Retain this

2020-10-19 15:58 UTC, mrinehart-r7 commented
@mgorny-morecode run `pip install pre-commit` and then `pre-commit install` - I noticed some of the changes here lost the formatting from Black (which is done at commit time with precommit)

2020-10-20 15:10 UTC, jschipp-r7 commented on insightconnect_plugin_runtime/plugin.py
> -    def envelope(message_type, input_message, log, success, output, error_message, state):
Will removing this break anything in product? @mrinehart-r7 - we might just want to keep the same behavior for `error_message` and add `ex` as an additional parameter to return. Trying to avoid product changes for expediency if we can

2020-10-23 00:02 UTC, r7-mgorny commented on samples/example/bin/icon_example
> -    #  if the plugin is running in Server mode(http).
This was removed by `make regenerate`. I will revert this :)

2020-11-06 19:50 UTC, mrinehart-r7 approved these changes

2020-11-06 20:02 UTC, gusingh-r7 approved these changes
LGTM!

2020-11-06 20:03 UTC, merged