[SOAR-6672] Add Timeout Preset
rapid7/komand-plugin-sdk-python pull request #96
Opened 2021-09-13 14:31 UTC by jrose-r7

Jira link: https://issues.corp.rapid7.com/browse/SOAR-6672
### Description

Add a Timeout preset to the ConnectionTestException within the plugin runtime. 

Cause: "The connection timed out."

Assistance: "Verify network connectivity."

### Motivation and Context

### How Has This Been Tested?

### Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have updated the documentation accordingly (if changes are required).
- [ ] I have tested the changes locally.

### Miscellaneous Details:

2021-09-13 14:46 UTC, pmara-r7 approved these changes
LGTM

2021-09-13 14:46 UTC, pmara-r7 commented
Seems like some of the CI stuff might be busted but the changes here look good

2021-09-13 14:54 UTC, mrinehart-r7 requested changes
Need to bump version & changelog and test locally

2021-09-20 16:29 UTC, mrinehart-r7 requested changes

2021-09-20 16:29 UTC, mrinehart-r7 commented on insightconnect_plugin_runtime/exceptions.py
> +        Preset.TIMEOUT: "This is likely a network error."
```suggestion
        Preset.TIMEOUT: "This is likely a network error. "
```
```suggestion
        Preset.TIMEOUT: "This is likely a network error."
```

2021-09-20 16:31 UTC, mrinehart-r7 requested changes

2021-09-20 16:31 UTC, mrinehart-r7 commented on insightconnect_plugin_runtime/exceptions.py
> +
```suggestion
```

2021-09-20 16:31 UTC, mrinehart-r7 commented on insightconnect_plugin_runtime/exceptions.py
> +
For PEP8 compliance

2021-09-20 16:32 UTC, mrinehart-r7 commented
<img width="1230" alt="Screen Shot 2021-09-20 at 10 12 55 AM" src="https://user-images.githubusercontent.com/32079048/134039396-e364da9c-ac7f-4829-9d0e-02ff796e0539.png">

2021-09-20 20:34 UTC, pmara-r7 approved these changes

2021-09-21 19:16 UTC, mrinehart-r7 requested changes

2021-09-21 19:16 UTC, mrinehart-r7 commented on insightconnect_plugin_runtime/exceptions.py
> +        Preset.TIMEOUT: "This is likely a network error."
```suggestion
        Preset.TIMEOUT: "This is likely a network error. "
```

2021-09-21 20:43 UTC, mrinehart-r7 approved these changes

2021-09-21 20:43 UTC, mrinehart-r7 approved these changes

2021-09-21 20:50 UTC, merged